"""
Proactive Insights API

Exposes insights generated by the BackgroundResearchAgent (and other autonomous agents)
to the frontend.
"""

from typing import List, Dict, Any, Optional
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from backend.app.memory_store import CaseMemoryStore

router = APIRouter()

class Insight(BaseModel):
    type: str
    confidence: float
    description: str
    action_item: str
    source_ids: List[str]
    created_at: str

class InsightsResponse(BaseModel):
    insights: List[Insight]
    count: int

def get_memory_store():
    return CaseMemoryStore()

@router.get("/{case_id}", response_model=InsightsResponse)
async def get_case_insights(
    case_id: str,
    store: CaseMemoryStore = Depends(get_memory_store)
):
    """
    Get all proactive insights for a case.
    """
    memory = store.load(case_id)
    insights_data = memory.get("proactive_insights", [])
    
    return InsightsResponse(
        insights=insights_data,
        count=len(insights_data)
    )

@router.post("/{case_id}", response_model=Dict[str, str])
async def add_insight(
    case_id: str,
    insight: Insight,
    store: CaseMemoryStore = Depends(get_memory_store)
):
    """
    Manually add an insight (internal use or testing).
    """
    memory = store.load(case_id)
    current_insights = memory.get("proactive_insights", [])
    
    # Add new insight
    current_insights.append(insight.dict())
    
    # Save back to memory
    memory["proactive_insights"] = current_insights
    store.save(case_id, memory)
    
    return {"status": "success", "message": "Insight added"}
